#!/usr/bin/env python
import sys
from os import path

sys.path.insert(0, path.abspath(path.join(__file__, '..', '..')))
sys.path.insert(0, path.abspath(path.join(__file__, '..', '..', 'forge-dependencies')))

from forge import main

main.with_error_handler(main.run)()
